package io.github.dongyuzhao.composecodeblock

// GENERATED by scripts/gen-compose-goldens.mjs from
// packages/shared/code-block-core/fixtures/code-snippets.json. Do not edit by hand.

internal data class GoldenCodeSnippetEntry(
    val id: String,
    val language: String,
    val code: String,
    val fontSizeSp: Float
)

internal val goldenCodeSnippets: List<GoldenCodeSnippetEntry> = listOf(
    GoldenCodeSnippetEntry("javascript-basic", "javascript", "const answer = 42;\nfunction greet(name) {\n  return `hello, \${name}`;\n}", 14f),
    GoldenCodeSnippetEntry("javascript-escapes", "javascript", "// Escapes keep their own color.\nconst MAX_RETRIES = 3;\nconst message = \"line\\nnext\";\nconst matcher = /\\w+\\s+code/;\nconsole.log(new Widget(message), matcher, MAX_RETRIES);", 14f),
    GoldenCodeSnippetEntry("jsx-element", "jsx", "const view = (\n  <section title=\"Status\">\n    Ready\n  </section>\n);", 14f),
    GoldenCodeSnippetEntry("typescript-generic", "typescript", "type Result<T> = { ok: true; value: T };\n\nexport function unwrap<T>(result: Result<T>): T {\n  return result.value;\n}", 14f),
    GoldenCodeSnippetEntry("tsx-component", "tsx", "type Props = { active: boolean };\nconst Badge = ({ active }: Props) => (\n  <strong>{active ? \"on\" : \"off\"}</strong>\n);", 14f),
    GoldenCodeSnippetEntry("python-escapes", "python", "class Greeter:\n    def message(self) -> str:\n        return \"line\\nnext\"", 14f),
    GoldenCodeSnippetEntry("kotlin-compose", "kotlin", "@Composable\nfun Greeting(name: String) {\n    Text(\"Hello, \$name\")\n}", 14f),
    GoldenCodeSnippetEntry("kotlin-scopes", "kotlin", "package demo\nfun scan(input: String): Boolean {\nloop@ for (ch in input) {\nif (ch == 'x') return Regex(\"\\\\d+\").matches(input)\n}}", 14f),
    GoldenCodeSnippetEntry("swift-literals", "swift", "let enabled = true\nlet matcher = /\\w+/\nvalues.forEach { value in\n    print(value)\n}", 14f),
    GoldenCodeSnippetEntry("bash-script", "bash", "#!/usr/bin/env bash\nname=\"world\"\necho \"Hello, \${name}\"", 14f),
    GoldenCodeSnippetEntry("c-main", "c", "#include <stdio.h>\nint main(void) {\n  return 0;\n}", 14f),
    GoldenCodeSnippetEntry("css-rule", "css", ".button {\n  color: #0a7;\n  display: grid;\n}", 14f),
    GoldenCodeSnippetEntry("go-function", "go", "package main\nfunc greet(name string) string {\n  return \"Hello, \" + name\n}", 14f),
    GoldenCodeSnippetEntry("html-element", "html", "<main class=\"app\">\n  <h1>Hello</h1>\n</main>", 14f),
    GoldenCodeSnippetEntry("java-record", "java", "record User(String name) {\n  boolean active() { return true; }\n}", 14f),
    GoldenCodeSnippetEntry("json-config", "json", "{\n  \"name\": \"code-block\",\n  \"enabled\": true\n}", 14f),
    GoldenCodeSnippetEntry("markdown-document", "markdown", "# Hello\n\nUse *emphasis*, **strong**, and `code`.\nRead the [docs](https://example.com).", 14f),
    GoldenCodeSnippetEntry("ruby-method", "ruby", "def greet(name)\n  \"Hello, #{name}\"\nend", 14f),
    GoldenCodeSnippetEntry("rust-function", "rust", "fn greet(name: &str) -> String {\n  format!(\"Hello, {name}\")\n}", 14f)
)
